[project]
name = "analytics"
version = "0.1.0"
description = "This package contains the analytics module for data processing and analysis for plenartrend."
requires-python = ">=3.14"
dependencies = [
    "sqlalchemy[asyncio]>=2.0.44",
    "asyncpg>=0.31.0",
    "alembic>=1.11.1",
    "pydantic>=2.7.6",
    "pydantic-settings>=2.2.1",
    "confluent-kafka>=2.4.0",
    "podi>=0.1.0",
    "hashrr>=0.1.0",
    "pipeline>=0.1.0",
    "langchain>=1.1.2",
    "langchain-openai>=1.1.0",
    "langchain-text-splitters>=1.0.0",
    "openai>=2.9.0",
    "torch>=2.9.1",
    "sentence-transformers>=5.1.2",
    "scikit-learn>=1.7.2",
    "matplotlib>=3.10.7",
    "pgvector>=0.4.2",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pre-commit>=4.0.1",
    "ruff>=0.7.3",
    "pytest>=7.4.0"
]
[tool.uv.workspace]
members = ["packages/*"]

[tool.uv.sources]
podi = { workspace = true }
pipeline = { workspace = true }
hashrr = { workspace = true }
torch = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py313"

lint.select = ["E", "F", "W", "I"]
fix = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
docstring-code-format = true
skip-magic-trailing-comma = false

preview = true

[tool.ruff.lint.isort]
combine-as-imports = true
force-single-line = false

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --tb=short"
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
