"""create schema

Revision ID: 23824f661f08
Revises:
Create Date: 2026-01-02 00:57:19.149214

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23824f661f08"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

latch_type_enum = postgresql.ENUM(
    "WORKING",
    "FINISHED",
    name="latch_type",
)


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hashrr_instances",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hashrr_heartbeats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("hashrr_instance_id", sa.Integer(), nullable=False),
        sa.Column("heartbeat", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["hashrr_instance_id"], ["hashrr_instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # latch_type_enum.create(op.get_bind(), checkfirst=True)

    op.create_table(
        "activity_latches",
        sa.Column("id", sa.Integer, primary_key=True, autoincrement=True),
        sa.Column(
            "latch",
            latch_type_enum,
            server_default=sa.text("'WORKING'"),
            nullable=False,
        ),
        sa.Column(
            "activity_id",
            sa.Integer,
            nullable=False,
        ),
        sa.Column(
            "hasharr_instance_id",
            sa.Integer,
            sa.ForeignKey("hashrr_instances.id", ondelete="SET NULL"),
        ),
        sa.Column(
            "created",
            sa.DateTime,
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("updated", sa.DateTime),
        sa.Column("processed", sa.DateTime),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("HashrrHeartbeats")
    op.drop_table("HashrrInstances")
    op.drop_table("activity_latches")

    latch_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
